import { useEffect, useState } from 'react'
import { FileText } from 'lucide-react'
import { getAllInvoices } from '@/api/invoices'
import Table from '@/components/ui/Table'
import type { Column } from '@/components/ui/Table'
import Modal from '@/components/ui/Modal'
import { formatCurrency, formatDate } from '@/utils'
import type { InvoiceResponse } from '@/types'

function Field({ label, value }: { label: string; value: string }) {
  return (
    <div className="space-y-1">
      <p className="text-[11px] font-bold text-gray-400 uppercase tracking-widest">{label}</p>
      <p className="text-sm font-semibold text-gray-900">{value || '—'}</p>
    </div>
  )
}

export default function InvoicesPage() {
  const [invoices, setInvoices] = useState<InvoiceResponse[]>([])
  const [isLoading, setIsLoading] = useState(true)
  const [selected, setSelected]  = useState<InvoiceResponse | null>(null)

  useEffect(() => {
    getAllInvoices()
      .then(res => setInvoices(res.data.data))
      .finally(() => setIsLoading(false))
  }, [])

  const columns: Column<InvoiceResponse>[] = [
    { key: 'invoiceNumber',   header: 'Invoice No',   render: r => <span className="font-bold text-gray-900 text-xs">{r.invoiceNumber}</span> },
    { key: 'gcNo',            header: 'GC No',        render: r => <span className="font-mono text-xs text-gray-600">{r.gcNo}</span> },
    { key: 'customer',        header: 'Customer',     render: r => <span className="font-semibold text-gray-800">{r.customer}</span> },
    { key: 'destination',     header: 'Destination' },
    { key: 'invoiceDate',     header: 'Invoice Date', render: r => formatDate(r.invoiceDate) },
    { key: 'invoiceAmount',   header: 'Amount',       render: r => <span className="font-semibold text-primary-700">{formatCurrency(r.invoiceAmount)}</span> },
    { key: 'totalFreight',    header: 'Freight',      render: r => formatCurrency(r.totalFreight) },
    { key: 'generatedByName', header: 'Generated By', render: r => <span className="text-gray-500">{r.generatedByName}</span> },
    { key: 'createdAt',       header: 'Date',         render: r => formatDate(r.createdAt) },
  ]

  return (
    <div className="space-y-5">
      <p className="text-xs text-gray-400 font-medium">
        {isLoading ? 'Loading…' : `${invoices.length} invoice${invoices.length !== 1 ? 's' : ''}`}
      </p>

      <Table
        columns={columns}
        data={invoices}
        isLoading={isLoading}
        onRowClick={setSelected}
        emptyMessage="No invoices yet. Generate invoices from the Shipments page."
        emptyIcon={<FileText size={36} />}
      />

      {selected && (
        <Modal isOpen onClose={() => setSelected(null)} title={`Invoice ${selected.invoiceNumber}`} size="md">
          <div className="p-6 space-y-5">
            {/* Summary header */}
            <div className="bg-primary-50 rounded-xl p-4 flex items-center justify-between">
              <div>
                <p className="text-xs font-bold text-primary-600 uppercase tracking-wide">Invoice Amount</p>
                <p className="text-2xl font-bold text-primary-700 mt-1">{formatCurrency(selected.invoiceAmount)}</p>
              </div>
              <div className="w-12 h-12 bg-primary-100 rounded-xl flex items-center justify-center">
                <FileText size={22} className="text-primary-600" />
              </div>
            </div>
            <div className="grid grid-cols-2 gap-x-6 gap-y-4">
              <Field label="Invoice Number"  value={selected.invoiceNumber} />
              <Field label="Invoice Date"    value={formatDate(selected.invoiceDate)} />
              <Field label="GC No"           value={selected.gcNo} />
              <Field label="Customer"        value={selected.customer} />
              <Field label="Destination"     value={selected.destination} />
              <Field label="Total Freight"   value={formatCurrency(selected.totalFreight)} />
              <Field label="Generated By"    value={selected.generatedByName} />
              <Field label="Created At"      value={formatDate(selected.createdAt)} />
              {selected.remarks && (
                <div className="col-span-2">
                  <Field label="Remarks" value={selected.remarks} />
                </div>
              )}
            </div>
          </div>
        </Modal>
      )}
    </div>
  )
}
