import { useEffect, useState } from 'react'
import { FileText } from 'lucide-react'
import { getAllInvoices } from '@/api/invoices'
import Table from '@/components/ui/Table'
import type { Column } from '@/components/ui/Table'
import Modal from '@/components/ui/Modal'
import { formatCurrency, formatDate } from '@/utils'
import type { InvoiceResponse } from '@/types'

function Field({ label, value }: { label: string; value: string }) {
  return (
    <div>
      <p className="text-xs text-gray-500 font-medium uppercase tracking-wide">{label}</p>
      <p className="text-sm text-gray-900 font-medium mt-0.5">{value}</p>
    </div>
  )
}

export default function InvoicesPage() {
  const [invoices, setInvoices] = useState<InvoiceResponse[]>([])
  const [isLoading, setIsLoading] = useState(true)
  const [selected, setSelected] = useState<InvoiceResponse | null>(null)

  useEffect(() => {
    getAllInvoices()
      .then(res => setInvoices(res.data.data))
      .finally(() => setIsLoading(false))
  }, [])

  const columns: Column<InvoiceResponse>[] = [
    { key: 'invoiceNumber', header: 'Invoice No', render: r => <span className="font-medium text-gray-900">{r.invoiceNumber}</span> },
    { key: 'gcNo', header: 'GC No' },
    { key: 'customer', header: 'Customer' },
    { key: 'destination', header: 'Destination' },
    { key: 'invoiceDate', header: 'Invoice Date', render: r => formatDate(r.invoiceDate) },
    { key: 'invoiceAmount', header: 'Amount', render: r => formatCurrency(r.invoiceAmount) },
    { key: 'totalFreight', header: 'Total Freight', render: r => formatCurrency(r.totalFreight) },
    { key: 'generatedByName', header: 'Generated By' },
    { key: 'createdAt', header: 'Created', render: r => formatDate(r.createdAt) },
  ]

  return (
    <div className="space-y-5">
      <div className="flex items-center justify-between">
        <p className="text-sm text-gray-500">{invoices.length} invoice{invoices.length !== 1 ? 's' : ''}</p>
      </div>

      <Table
        columns={columns}
        data={invoices}
        isLoading={isLoading}
        onRowClick={row => setSelected(row)}
        emptyMessage="No invoices yet. Generate invoices from the Shipments page."
        emptyIcon={<FileText size={40} />}
      />

      {selected && (
        <Modal isOpen onClose={() => setSelected(null)} title={`Invoice ${selected.invoiceNumber}`} size="md">
          <div className="p-5 grid grid-cols-2 gap-4">
            <Field label="Invoice Number" value={selected.invoiceNumber} />
            <Field label="Invoice Date" value={formatDate(selected.invoiceDate)} />
            <Field label="GC No" value={selected.gcNo} />
            <Field label="Customer" value={selected.customer} />
            <Field label="Destination" value={selected.destination} />
            <Field label="Total Freight" value={formatCurrency(selected.totalFreight)} />
            <Field label="Invoice Amount" value={formatCurrency(selected.invoiceAmount)} />
            <Field label="Generated By" value={selected.generatedByName} />
            <Field label="Created At" value={formatDate(selected.createdAt)} />
            {selected.remarks && <div className="col-span-2"><Field label="Remarks" value={selected.remarks} /></div>}
          </div>
        </Modal>
      )}
    </div>
  )
}
